### ISSUE TITLE
( Question ) cotm launcher

### ISSUE THREAD

**Issue by SDUBZ** [elytra/CotM-Launcher#2]
Hello
i was just wondering how i change the name of launcher i have tried editing launcher proerties
in CotM-Launcher-master\launcher\src\main\resources\com\skcraft\launcher\lang
but it didn't seem to update name of launcher

Please reply asap
Thanks in advance

**Comment by unascribed** [comment]
Please check the [SKCraft Wiki](https://github.com/SKCraft/Launcher/wiki) for how to customize the launcher.

**Comment by SDUBZ** [comment]
i did and it didnt work or go into great detail on what to change so i thought it must be just the top most name that had cotm launcher so i changed it to a different title and did clean build to update everything and it didnt change at all

**Comment by unascribed** [comment]
Everything you need to change, **as mentioned by the SKCraft wiki**, is in this directory: https://github.com/elytra/CotM-Launcher/tree/master/launcher/src/main/resources/com/skcraft/launcher

**Comment by SDUBZ** [comment]
got it all working now thanks for you help :D
