### ISSUE TITLE
[SKCraft Support, Not CotM] Pack fails to launch due to missing FML relauncher

### ISSUE THREAD

**Issue by SDUBZ** [elytra/CotM-Launcher#3]
i have downloaded all of my packs before sharing my launcher and all of them functioned correctly but anyone else using the launcher would get the following error
https://pastebin.com/P1K4MxMZ

but myself cant replicate

any help or advice would be appreciated

thanks in advance

**Comment by unascribed** [comment]
Did you place the .jar Forge installer into the "loaders" directory? (NOT the exe)

**Comment by SDUBZ** [comment]
yes i placed needed forge.x.x.xinstaller.jar in loaders folder

**Comment by SDUBZ** [comment]
also i noticed once starting fresh with modpack maker i got this while setting up again with a pack 
java.io.IOException: 2 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by unascribed** [comment]
What are you using for hosting?

**Comment by SDUBZ** [comment]
this was just launching pack so i could setup frsh files on my computer to eliminate corrupted files etc and its the installer grabbing files from either forge or mojangs hosting

**Comment by unascribed** [comment]
...That's not how SKCraft works. You need to upload the pack to a host you control that offers plain HTTP.

**Comment by SDUBZ** [comment]
dude look whats failing to setup in instance http://puu.sh/xjlH1/415f748d1f.png

**Comment by unascribed** [comment]
Okay, you never said what file was failing.

I've never had any issue like this with SKCraft and am not sure where to start debugging this.

**Comment by asiekierka** [comment]
@unascribed The Starchasers had a similar issue with ASM not downloading, and we don't know what's causing it either

**Comment by SDUBZ** [comment]
well im gonna try earlier forge and see if its jar realted okay :)

**Comment by falkreon** [comment]
Since this is definitely an SKCraft error I'm closing out this issue. If you need further help on this one, either catch us in IRC or address it directly with SKCraft.

**Comment by asiekierka** [comment]
http://github.com/SKCraft/Launcher
